SECTION_CODE = "CODE"
SECTION_INPUT = "INPUT"
SECTION_PACKAGES = "PACKAGES"
SECTION_OUTPUT = "OUTPUT"
SECTION_META = "META"
SECTION_SETUP = "SETUP"

ALLOWED_SECTIONS = {
    SECTION_CODE,
    SECTION_INPUT,
    SECTION_PACKAGES,
    SECTION_OUTPUT,
    SECTION_META,
    SECTION_SETUP,
}

META_INPUT_SOURCE_KEY = "input_source"
META_OUTPUT_SOURCE_KEY = "output_source"
META_SOURCE_VALUES = {"textbook", "generated_sample", "empty"}

META_OUTPUT_DETERMINISM_KEY = "output_determinism"
META_OUTPUT_DETERMINISM_VALUES = {"deterministic", "nondeterministic"}
DEFAULT_META_OUTPUT_DETERMINISM = "deterministic"
LEGACY_META_MODE_KEY = "mode"

META_STDIN_EXHAUSTION_KEY = "stdin_exhaustion"
META_STDIN_EXHAUSTION_VALUES = {"deny", "accept"}
DEFAULT_META_STDIN_EXHAUSTION = "deny"

META_CODE_TYPE_KEY = "code_type"
CODE_TYPE_COMPLETE = "COMPLETE_CODE"
CODE_TYPE_INCOMPLETE_SNIPPET = "INCOMPLETE_SNIPPET"
CODE_TYPE_ERROR_FINDING = "ERROR_FINDING"
META_CODE_TYPE_VALUES = {
    CODE_TYPE_COMPLETE,
    CODE_TYPE_INCOMPLETE_SNIPPET,
    CODE_TYPE_ERROR_FINDING,
}
DEFAULT_META_CODE_TYPE = CODE_TYPE_COMPLETE

META_EXECUTION_MODE_KEY = "execution_mode"
EXECUTION_MODE_SCRIPT = "script"
EXECUTION_MODE_REPL = "repl"
EXECUTION_MODE_VALUES = {
    EXECUTION_MODE_SCRIPT,
    EXECUTION_MODE_REPL,
}

META_ENUM_VALUES = {
    META_INPUT_SOURCE_KEY: META_SOURCE_VALUES,
    META_OUTPUT_SOURCE_KEY: META_SOURCE_VALUES,
    META_OUTPUT_DETERMINISM_KEY: META_OUTPUT_DETERMINISM_VALUES,
    LEGACY_META_MODE_KEY: META_OUTPUT_DETERMINISM_VALUES,
    META_STDIN_EXHAUSTION_KEY: META_STDIN_EXHAUSTION_VALUES,
    META_CODE_TYPE_KEY: META_CODE_TYPE_VALUES,
    META_EXECUTION_MODE_KEY: EXECUTION_MODE_VALUES,
}

PARSER_ERROR_MISSING_SECTION = "missing_section"
PARSER_ERROR_DUPLICATE_SECTION = "duplicate_section"
PARSER_ERROR_CONTENT_BEFORE_HEADER = "content_before_header"
PARSER_ERROR_EMPTY_CODE = "empty_code"
PARSER_ERROR_INVALID_META = "invalid_meta"
PARSER_ERROR_UNKNOWN_SECTION = "unknown_section"
PARSER_ERROR_READ_ERROR = "read_error"

PARSER_ERROR_TYPES = {
    PARSER_ERROR_MISSING_SECTION,
    PARSER_ERROR_DUPLICATE_SECTION,
    PARSER_ERROR_CONTENT_BEFORE_HEADER,
    PARSER_ERROR_EMPTY_CODE,
    PARSER_ERROR_INVALID_META,
    PARSER_ERROR_UNKNOWN_SECTION,
    PARSER_ERROR_READ_ERROR,
}

STATUS_PASSED = "passed"
STATUS_FAILED = "failed"
STATUS_SKIPPED = "skipped"

RESULT_STATUSES = {
    STATUS_PASSED,
    STATUS_FAILED,
    STATUS_SKIPPED,
}

CATEGORY_PARSE_ERROR = "parse_error"
CATEGORY_SYNTAX_ERROR = "syntax_error"
CATEGORY_NAME_ERROR = "name_error"
CATEGORY_MODULE_NOT_FOUND = "module_not_found"
CATEGORY_MISSING_REQUIRED_FILE = "missing_required_file"
CATEGORY_INPUT_REQUIRED_OR_INVALID = "input_required_or_invalid"
CATEGORY_TIMEOUT = "timeout"
CATEGORY_OUTPUT_MISMATCH = "output_mismatch"
CATEGORY_RUNTIME_ERROR = "runtime_error"
CATEGORY_UNSUPPORTED_PACKAGE = "unsupported_package"
CATEGORY_ENVIRONMENT_DEPENDENT = "environment_dependent"
CATEGORY_EXECUTOR_INPUT_ERROR = "executor_input_error"
CATEGORY_INCOMPLETE_SNIPPET = "incomplete_snippet"
CATEGORY_ERROR_FINDING = "error_finding"
CATEGORY_RUNNER_ERROR = "runner_error"

RESULT_CATEGORIES = {
    CATEGORY_PARSE_ERROR,
    CATEGORY_SYNTAX_ERROR,
    CATEGORY_NAME_ERROR,
    CATEGORY_MODULE_NOT_FOUND,
    CATEGORY_MISSING_REQUIRED_FILE,
    CATEGORY_INPUT_REQUIRED_OR_INVALID,
    CATEGORY_TIMEOUT,
    CATEGORY_OUTPUT_MISMATCH,
    CATEGORY_RUNTIME_ERROR,
    CATEGORY_UNSUPPORTED_PACKAGE,
    CATEGORY_ENVIRONMENT_DEPENDENT,
    CATEGORY_EXECUTOR_INPUT_ERROR,
    CATEGORY_INCOMPLETE_SNIPPET,
    CATEGORY_ERROR_FINDING,
    CATEGORY_RUNNER_ERROR,
}
